### ISSUE TITLE
read Permission error 

### ISSUE THREAD

**Issue by wstrange** [vaijab/fedora-gce-image#1]
I am getting a read permission error when trying to add your image:

gcutil addimage fedora-20 gs://cloud-images/fedora-20-latest.tar.gz

INFO: Waiting for insert of image fedora-20. Sleeping for 3s.
ERROR: PERMISSIONS_ERROR: Required 'read' permission for 'rawDisk.source'

BTW - thanks for putting this together!!!

**Comment by vaijab** [comment]
@wstrange should be fixed now. I forgot to tick a 'Shared Publicly' box on this particular cloud storage object. Sorry about that and thanks for letting me know!

**Comment by wstrange** [comment]
Thanks!!!!
